#For generate documentation install "https://github.com/realm/jazzy" and use the command `jazzy` in terminal

output: ../../docs/docs
clean: true
author: SDOS
author_url: https://sdos.es
module: SDOSEnvironment
github_url: https://svrgitpub.sdos.es/iOS/SDOSFirebase
github_file_prefix: https://svrgitpub.sdos.es/iOS/SDOSFirebase/tree/master
skip_undocumented: true
xcodebuild_arguments: [-workspace, SDOSFirebaseSample.xcworkspace, -scheme, SDOSFirebase]
swift_version: 5.0.0
exclude:
  - "**/*.h"
  - "**/*.m"